### ISSUE TITLE
How can I remove NAME field in signup UI?

### ISSUE THREAD

**Issue by wangbourne** [ParsePlatform/ParseUI-Android#103]
it's a similar question with  https://github.com/ParsePlatform/ParseUI-Android/issues/43. In that task it seems already done.

However, I tried this function by introducing
compile 'com.parse:parseui-login-android:0.0.1'
compile 'com.parse:parseui-widget-android:0.0.1'

The name field is still there. Is it because you haven't update these two?

**Comment by wangmengyan95** [comment]
Hi @wangbourne, we have not updated the repo on maven yet. Since we are working on RecycleViewAdapter, we want to include that in the new release. If you are in a hurry, you can always clone our repo and use the latest source code directly. Always remember, the master branch is not guaranteed to be stable. Make sure you do not include it in your production.
