### ISSUE TITLE
Support Google+ Login

### ISSUE THREAD

**Issue by bullest** [ParsePlatform/ParseUI-Android#36]
Do you have any plan to add Google login?

**Comment by drhuanliu** [comment]
We have a couple of our users requesting Google login as well. +1 request to add Google login

**Comment by akhyrul** [comment]
Google Login +1 :+1:

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Hello guys , in order to make ParseLoginUI work Google Login, we need our backend to support Google Login API service which is not so easy to do right now. You can definitely hack with ParseLoginUI and add support for that, but unfortunately the login/logout can not be handled by ParseUser.
I will close this issue for now, but please keep an eye on our repo (Parse, ParseUI). Once we add third party auth support for ParseUser, you can use ParseUser and ParseLoginUI for your Google Login API service.

**Comment by jhansche** [comment]
@wangmengyan95 looks like this is supported on the backend now, right?
https://github.com/ParsePlatform/parse-server/blob/master/src/authDataManager/google.js

**Comment by ashish-naik** [comment]
Is this integration going to happen?
