### ISSUE TITLE
upgrade to gradle 2.4

### ISSUE THREAD

**Issue by hsavit1** [ParsePlatform/ParseUI-Android#42]

**Comment by hsavit1** [comment]
parse ui is set at gradle 1.0, but the current gradle version is 2.4

is there any way you can upgrade this ?

**Comment by pseudozach** [comment]
Error:Gradle 2.4 requires Android Gradle plugin 1.2.0 (or newer)  but project is using version 1.0.0.
Please use Android Gradle plugin 1.2.0 or newer.
and ParseLoginUI fails with android gradle version > 1.0

any updates on this?

**Comment by wangmengyan95** [comment]
Hello @pseudozach, @hsavit1, previously the problem was Gradle 2.4 needed to use Android Gradle plugin 1.2.0, but in Android Gradle plugin 1.2, we have to compile facebook SDK in our gradle file instead of provided it, since facebook SDK is an aar not a jar.
But in Gradle plugin 1.3.1, problem solved, check the PR #54.
