### ISSUE TITLE
Using native app authetication for twitter login

### ISSUE THREAD

**Issue by divyatman** [ParsePlatform/ParseUI-Android#44]
I am trying to integrate twitter login and sample apps show a web like pop up for signin instead of a single sign on experience that we get with twitter SDK

**Comment by wangmengyan95** [comment]
@divyatman thanks for opening this issue. The situation is we use ParseTwitterUtils to handle twitter login for ParseUI-Android. Since ParseTwitterUtils does not support the native Twitter app, ParseUI-Android can not do that. Once ParseTwitterUtils add that support, we will update ParseUI-Android and integrate it with native Twitter app. So I will close this issue right now.

**Comment by MounikaTec** [comment]
In Android right now it's opening webview for entering twitter credentials but i don't want that if already user has native twitter app logged in I want to go directly there instead of opening web view .I am using xamarin.auth .How to work on that.please provide me solution.
