### ISSUE TITLE
Can I use ParseLoginUI for my own Login API service ?

### ISSUE THREAD

**Issue by korrio** [ParsePlatform/ParseUI-Android#45]

**Comment by wangmengyan95** [comment]
Hello @korrio , in order to make `ParseLoginUI` work with your custom Login API service, we need our backend to support your Login API service which is not so easy to do right now. You can definitely hack with `ParseLoginUI` and add support for your Login API service, but unfortunately the login/logout can not be handled by `ParseUser`.
I will close this issue for now, but please keep an eye on our repo ([Parse](https://github.com/ParsePlatform/Parse-SDK-Android), [ParseUI](https://github.com/ParsePlatform/ParseUI-Android)). Once we add third party auth support for `ParseUser`, you can use `ParseUser` and `ParseLoginUI` for your own Login API service.
